### ISSUE TITLE
Click the web service endpoint, application error.

### ISSUE THREAD

**Issue by zedy-wj** [tonybaloney/django-on-azure#35]
**Describe the issue:**
After `azd deploy`, click the endpoint of service web, you will get the error below:
![image](https://user-images.githubusercontent.com/81678720/230873243-c2f47715-f97e-494d-bf39-1b6fabf64008.png)

**Repro Steps:**

1. azd init -t <template_name>
2. azd package
3. azd provision
4. azd deploy, click the endpoint of service `web`.

**Environment:**
OS: Windows
Azd version: azd version 0.8.0-beta.1-daily.2689578 (commit 3b28fc8f84717d732f646a3e3b9521204f122112)

**Expected behavior:**
After deployment, the page can be opened normally.

@rajeshkamal5050, @tonybaloney for notification.

**Comment by kjaymiller** [comment]
@zedy-wj - what region are you using... I tried using one of my normal choices (WestUS) and ran into some region errors.

I saw you're a part of MSFT - I've noticed that I run into errors deploying that are sometimes region based... I just tried to reproduce using EastUS and was able to deploy via azd.

### Notes:
- Using azd version 0.7.0-beta-1 Trying again after updating AZD

**Comment by zedy-wj** [comment]
@kjaymiller - Thanks for your feedback. The region I used is also `EastUS`. I tried again with this azd version: 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01) and got the same error. 
What you mentioned: `was able to deployed via azd`, after the deployment is complete, do you click the web endpoint to view it? There is nothing wrong with the `azd deploy` command itself. The result of my execution is shown in the figure:
 
<img width="509" alt="image" src="https://user-images.githubusercontent.com/81678720/231037212-991ed3a6-de95-4a89-a0ab-c9f4a05b1c05.png">

But we found this problem after clicking the endpoint.

**Comment by kjaymiller** [comment]
Yes I was able to view the website as expected.

Were you able to access the streaming logs either in VS Code or in the Azure Portal?

**Comment by zedy-wj** [comment]
It's `Platform logs` in the Azure Portal:
![image](https://user-images.githubusercontent.com/81678720/231357161-eaad125b-3303-44f1-85e0-db2c506110eb.png)

It's `Application logs` in the Azure Portal:
![image](https://user-images.githubusercontent.com/81678720/231357293-008528c8-1b5b-4eb6-9579-5cdeed3e9274.png)

It's `Http Server Errors` in the Azure Portal:
![image](https://user-images.githubusercontent.com/81678720/231358202-31c0601a-4493-44c5-bd16-01a786d0282e.png)

Let's me know if you need more info.

**Notes:** We found that the page opened in the Linux environment is normal, what environment are you using?
![image](https://user-images.githubusercontent.com/81678720/231367155-a7543785-cd2c-49d8-95e8-27a8b83387d3.png)

**Comment by kjaymiller** [comment]
Yes and it looks like there is a carriage return being added to the end of the script that is being added. 

`Unknown command: 'migrate\r'. Did you mean migrate?`

This is being called in [`demo-application/startup.sh`](https://github.com/tonybaloney/django-on-azure/blob/main/demo-application/startup.sh).  The `\r` is halting the build.

Was this file edited while on your system? I wonder if the files were modified silently when opened on your machine swapping the `\n` with `\r`.

**Comment by zedy-wj** [comment]
@kjaymiller - Thanks for your help, we can open the web page normally!

**Comment by zedy-wj** [comment]
Closed it as completed.
